import "../styles/globals.css";
import { MoralisProvider } from "react-moralis";
import Header from "./components/Header";
import Head from "next/head";

export default function App({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>NFT Marketplace</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<MoralisProvider
				appId={process.env.NEXT_PUBLIC_APP_ID}
				serverUrl={NEXT_PUBLIC_SERVER_URL}
			>
				<Header />
				<Component {...pageProps} />
			</MoralisProvider>
		</>
	);
}
